### ISSUE TITLE
Copyrights violation

### ISSUE THREAD

**Issue by 4144** [Spell-Master/Arcadia#4]
This project using hercules sources with removed copyrights. Original sources is here https://github.com/HerculesWS/Hercules

Please return all copyrights back, or your project will be down.

**Comment by Spell-Master** [comment]
This project is nothing more than a backup of a personal job. I do not care what they weigh or do about it.
About rights have been removed, since it does use the hercules base, but as currently more than half of the code is independent of the predecessor. And with the course will be completely different.
However it was not stipulated that the code was created by someone, but rather that the modifications are being made. Because the repository needed a name to create, being used only as a backup.

**Comment by jguy1987** [comment]
Does not matter if modifications are being made or it's a backup. The license copylefts must be maintained as per the GNU GPL license. You are hosting a public repository. If you do not wish to maintain the copylefts, then you can make it a private repository. 

Else we have no choice but to report to GitHub. This is a clear violation of the GNU GPL that Hercules/rAthena/eAthena are released under.

**Comment by 4144** [comment]
@Spell-Master you used hercules source in previous commits. More your code over or less, it based on hercules, this mean copyrights must stand. You can name project as you witsh and add own or some one else copyrights too. But you cant remove existing copyrights.

Because GPL violation github may remove this repo.
